Vagrant.configure('2') do |config|
  config.vm.box = 'proxmox-ve-amd64'
  config.vm.provider :virtualbox do |vb|
    vb.linked_clone = true
    vb.memory = 2048
  end
  ip = '10.10.10.2'
  config.vm.network :private_network, ip: ip, auto_config: false
  config.vm.provision :shell, path: 'provision.sh', args: [ip]
end
